/****** Menampilkan Data Tindakan Lab  ******/
SELECT TOP 1000 [Kd_Inst]
      ,[Kd_SubInst]
      ,[KDKEL]
      ,[KELOMPOK]
      ,[TINDAKAN]
      ,[Jenis]
      ,[JenisTindakan]
      ,[KodeJenis]
      ,[Kode1]
      ,[Kode2]
      ,[Kd_SubTarif]
  FROM [SIMRS].[dbo].[TindakanLab]
  
  /****** Menampilkan Data Tarif Tindakan Lab  ******/
SELECT [Kd_Inst]
      ,[Kd_SubInst]
      ,[Kode1]
      ,[Kode2]
      ,[Ket1]
      ,[Kd_Kelas]
      ,[lDokter]
      ,[Harga_Bhn]
      ,[Js_RS]
      ,[Js_MedRS]
      ,[Js_MedL]
      ,[Js_MedTL]
      ,[Js_KSO]
      ,[SP_KSO]
      ,[lKet]
      ,[KdKel1]
      ,[Kd_Upf]
      ,[Kd_Transfer]
      ,[lBHP]
      ,[PajakDok]
      ,[lStlPajak]
      ,[lAktif]
      ,[Nil_Normal]
      ,[lPilih]
      ,[lHeader]
      ,[JenisTindakan]
      ,[Kode3]
      ,[KELOMPOK]
      ,[Cyto]
      ,[lCytoHarga_Bhn]
      ,[lCytoJs_RS]
      ,[lCytoJs_MedL]
      ,[lCytoJs_MedTL]
      ,[KodeJenis]
      ,[lReg]
      ,[lDrSpesialis]
      ,[KodeKelDokter]
      ,[lPaketTind]
      ,[KodeTind]
  FROM [SIMRS].[dbo].[TARIF]
  where Kd_Inst='3002'